CREATE TABLE tasks (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    COMPLITE BOOLEAN DEFAULT false,
    DATE_START DATETIME DEFAULT now(),
    DATE_END DATETIME DEFAULT now(),
    DATE_INSERT DATETIME DEFAULT now(),
    PRIMARY KEY (ID)    
)